version: "2.0"
networks:
  unqfynet:
    driver: bridge
services:
  unqfy:
    container_name: unqfy
    networks:
      - unqfynet
    build: ./UNQfy
    ports:
      - "7070:7070"
    environment:
      - LOGGING_API_HOST=${LOGGING_API_HOST}
      - NEWSLETTER_API_HOST=${NEWSLETTER_API_HOST}
      - SPOTIFY_API_HOST=${SPOTIFY_API_HOST}
      - MUSIX_MATCH_API_HOST=${MUSIX_MATCH_API_HOST}
      - SPOTIFY_TOKEN=${SPOTIFY_TOKEN}
      - MUSIX_MATCH_API_KEY=${MUSIX_MATCH_API_KEY}
      - TZ=${TZ}
  logging:
    container_name: logging
    networks:
      - unqfynet
    build: ./Logging
    ports:
      - "7080:7080"
    environment:
      - LOGGLY_TOKEN=${LOGGLY_TOKEN}
      - LOGGLY_SUBDOMAIN=${LOGGLY_SUBDOMAIN}
      - TZ=${TZ}
  newsletter:
    container_name: newsletter
    networks:
      - unqfynet
    build: ./Newsletter
    ports:
      - "7090:7090"
    environment:
      - TZ=${TZ}
      - UNQFY_API_HOST=${UNQFY_API_HOST}
      - TOKEN_PATH=${GMAIL_TOKEN_PATH}
      - CREDENTIALS_PATH=${GMAIL_CREDENTIALS_PATH}
  monitor:
    container_name: monitor
    networks:
      - unqfynet
    build: ./Monitor
    ports:
      - "7100:7100"
    depends_on:
      - unqfy
      - newsletter
      - logging
    environment:
      - TZ=${TZ}
      - UNQFY_API_HOST=${UNQFY_API_HOST}
      - LOGGING_API_HOST=${LOGGING_API_HOST}
      - NEWSLETTER_API_HOST=${NEWSLETTER_API_HOST}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}

