version: "2.0"
networks:
  unqfynet:
    driver: bridge
services:
  unqfy:
    container_name: unqfy
    networks:
      - unqfynet
    build: ./UNQfy
    ports:
      - "7070:7070"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - NEWSLETTER_API_HOST=http://newsletter:7090
      - LOGGING_API_HOST=http://logging:7080
  logging:
    container_name: logging
    networks:
      - unqfynet
    build: ./Logging
    ports:
      - "7080:7080"
    volumes:
      - ./Logging/logs:/usr/src/app/logs
    environment:
      - LOGGLY_TOKEN
      - LOGGLY_SUBDOMAIN=fenixcreworg
      - TZ=America/Argentina/Buenos_Aires
  newsletter:
    container_name: newsletter
    networks:
      - unqfynet
    build: ./Newsletter
    ports:
      - "7090:7090"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - UNQFY_API_HOST=http://unqfy:7070
  monitor:
    container_name: monitor
    networks:
      - unqfynet
    build: ./Monitor
    ports:
      - "7100:7100"
      - "80:80"
    depends_on:
      - unqfy
      - newsletter
      - logging
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - UNQFY_API_HOST=http://unqfy:7070
      - LOGGING_API_HOST=http://logging:7080
      - NEWSLETTER_API_HOST=http://newsletter:7090
      - DISCORD_WEBHOOK
