version: "2.0"
networks:
  unqfynet:
    external: true
services:
  unqfy:
    networks:
      unqfynet:
        ipv4_address: 172.20.0.20
    build: ./UNQfy
    ports:
      - "7070:7070"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - NEWSLETTER_API_HOST=http://newsletter:7090
      - LOGGING_API_HOST=http://logging:7080
  logging:
    networks:
      unqfynet:
        ipv4_address: 172.20.0.21
    build: ./Logging
    ports:
      - "7080:7080"
    volumes:
      - ./Logging/logs:/usr/src/app/logs
    environment:
      - LOGGLY_TOKEN=1047cead-58e2-4b98-a40d-df0e5ba00a7
      - LOGGLY_SUBDOMAIN=fenixcreworg
      - TZ=America/Argentina/Buenos_Aires
  newsletter:
    networks:
      unqfynet:
        ipv4_address: 172.20.0.22
    build: ./Newsletter
    ports:
      - "7090:7090"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - UNQFY_API_HOST=http://unqfy:7070
  monitor:
    networks:
      unqfynet:
        ipv4_address: 172.20.0.23
    build: ./Monitor
    ports:
      - "7100:7100"
      - "80:80"
    depends_on:
      - unqfy
      - newsletter
      - logging
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - UNQFY_HOST=http://172.20.0.20:7070
      - LOGGING_HOST=http://172.20.0.21:7080
      - NEWSLETTER_HOST=http://172.20.0.22:7090
      - DISCORD_WEBHOOK="https://discord.com/api/webhooks/907743539297927218/g8YD9YdoUx

# Con este tenes que crear la red antes: docker network create --gateway 172.20.0.1 --subnet 172.20.0.0/24 unqfynet
