version: "2.0"
networks:
  unqfynet:
    driver: bridge
services:
  unqfy:
    container_name: unqfy
    networks:
      - unqfynet
    build: ./UNQfy
    ports:
      - "7070:7070"
    environment:
      - LOGGING_API_HOST=http://logging:7080
      - NEWSLETTER_API_HOST=http://newsletter:7090
      - SPOTIFY_API_HOST=https://api.spotify.com/v1
      - MUSIX_MATCH_API_HOST=http://api.musixmatch.com/ws/1.1
      - SPOTIFY_TOKEN=
      - MUSIX_MATCH_API_KEY=
      - TZ=America/Argentina/Buenos_Aires
  logging:
    container_name: logging
    networks:
      - unqfynet
    build: ./Logging
    ports:
      - "7080:7080"
    environment:
      - LOGGLY_TOKEN=
      - LOGGLY_SUBDOMAIN=fenixcreworg
      - TZ=America/Argentina/Buenos_Aires
  newsletter:
    container_name: newsletter
    networks:
      - unqfynet
    build: ./Newsletter
    ports:
      - "7090:7090"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - UNQFY_API_HOST=http://unqfy:7070
      - TOKEN_PATH=./token.json
      - CREDENTIALS_PATH=./credentials.json
  monitor:
    container_name: monitor
    networks:
      - unqfynet
    build: ./Monitor
    ports:
      - "7100:7100"
    depends_on:
      - unqfy
      - newsletter
      - logging
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - UNQFY_API_HOST=http://unqfy:7070
      - LOGGING_API_HOST=http://logging:7080
      - NEWSLETTER_API_HOST=http://newsletter:7090
      - DISCORD_WEBHOOK=
